### ISSUE TITLE
VerticalSecondScale and a StaticLabelsFormatter - dies if primary and secondary scales differ

### ISSUE THREAD

**Issue by arober11** [jjoe64/GraphView#310]
Just tried setting a StaticLabelsFormatter on the Primary series, but the code blows up as the number of labels in the formatter, for the primary series differs to the number that the code has calculated it needs for the second vertical scale (already raised the copying of the primary labels as an issue #308).

    java.lang.ArrayIndexOutOfBoundsException: length=9; index=-12
            at com.jjoe64.graphview.helper.StaticLabelsFormatter.formatLabel(StaticLabelsFormatter.java:176)
            at com.jjoe64.graphview.GridLabelRenderer.calcLabelVerticalSecondScaleSize(GridLabelRenderer.java:760)
            at com.jjoe64.graphview.GridLabelRenderer.draw(GridLabelRenderer.java:811)
            at com.jjoe64.graphview.GraphView.onDraw(GraphView.java:296)
            at android.view.View.draw(View.java:15114)
            at android.view.View.updateDisplayListIfDirty(View.java:14048)

**Comment by jjoe64** [comment]
thanks for reporting
