### ISSUE TITLE
Not allowed bounds?

### ISSUE THREAD

**Issue by lukeskymuh** [jjoe64/GraphView#387]
Hi,

when I set my X bounds to:

```
graph.getViewport().setXAxisBoundsManual(true);
graph.getViewport().setMinX(0.18);
graph.getViewport().setMaxX(0.25);
```

my app crashes.

The same code with these bounds:
```
graph.getViewport().setXAxisBoundsManual(true);
graph.getViewport().setMinX(0.0);
graph.getViewport().setMaxX(0.25);
```

works.

are there any limitations for the bounds?

Best Regards 
Luke

**Comment by jjoe64** [comment]
Can you post the complete exception with stacktrace
Am 06.02.2016 11:43 schrieb "lukeskymuh" <notifications@github.com>:

**Comment by lukeskymuh** [comment]
is this what you mean with stacktrace?

`02-07 00:30:30.408 15272-15272/com.schmidt.lukas.weight E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.schmidt.lukas.weight, PID: 15272
                                                                        java.lang.RuntimeException: Unable to resume activity {com.schmidt.lukas.weight/com.schmidt.lukas.weight.CalibrationActivity}: java.lang.NullPointerException
                                                                            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2964)
                                                                            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2993)
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                            at android.os.Looper.loop(Looper.java:193)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5292)
                                                                            at java.lang.reflect.Method.invokeNative(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:515)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
                                                                            at dalvik.system.NativeStart.main(Native Method)
                                                                         Caused by: java.lang.NullPointerException
                                                                            at com.jjoe64.graphview.series.BaseSeries$1.<init>(BaseSeries.java:183)
                                                                            at com.jjoe64.graphview.series.BaseSeries.getValues(BaseSeries.java:170)
                                                                            at com.jjoe64.graphview.Viewport.calcCompleteRange(Viewport.java:574)
                                                                            at com.jjoe64.graphview.GraphView.onDataChanged(GraphView.java:278)
                                                                            at com.jjoe64.graphview.series.BaseSeries.resetData(BaseSeries.java:360)
                                                                            at com.schmidt.lukas.weight.CalibrationActivity.updateCalView(CalibrationActivity.java:388)
                                                                            at com.schmidt.lukas.weight.CalibrationActivity.onResume(CalibrationActivity.java:322)
                                                                            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)
                                                                            at android.app.Activity.performResume(Activity.java:5343)
                                                                            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2950)
                                                                            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2993) 
                                                                            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395) 
                                                                            at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                                            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
                                                                            at android.os.Handler.dispatchMessage(Handler.java:110) 
                                                                            at android.os.Looper.loop(Looper.java:193) 
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5292) 
                                                                            at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                            at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824) 
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640) 
                                                                            at dalvik.system.NativeStart.main(Native Method) `

**Comment by lukeskymuh** [comment]
The main reason why I try to use the manual bounds is that the graph does not update the automatic axis when I call the graphSeries.resetData function in the onCreate function of an ActionBarActivity. When I call it again with a button the axis is updated.

**Comment by lukeskymuh** [comment]
Hey Joe,

have you did you have alredy time to look at the problem? Or do you need any further information?

Best Regards 
Jan Klement

**Comment by jjoe64** [comment]
not sure, but i think this problem is already fixed
