### ISSUE TITLE
min /max x crash my app 

### ISSUE THREAD

**Issue by GeorgeSia** [jjoe64/GraphView#403]
Hello, I want to make a plotting app in real time. I've created the app and make it plot my data but i have an issue. If i don't set x axis manual, when i click to run my app, crashes immediately. If i set manual the x axis my app run until it reach the max x value and then crashes again. Any advice will be much more appreciated.
thank you very much.

My create method:
`protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_graph);

        editTextAddress = (EditText) findViewById(R.id.address);
        editTextPort = (EditText) findViewById(R.id.editText);
        textStatus = (TextView) findViewById(R.id.textStatus);
        editText2 = (EditText) findViewById(R.id.editText2);
        editText3 = (EditText) findViewById(R.id.editText3);
        editText4 = (EditText) findViewById(R.id.editText4);
        editText5 = (EditText) findViewById(R.id.editText5);
        sgraph1 = (Switch)  findViewById(R.id.switch1);
        sgraph2 = (Switch)  findViewById(R.id.switch2);
        graph1 = (GraphView) findViewById(R.id.graph);

        series= new LineGraphSeries<>(new DataPoint[]{});
        series2= new LineGraphSeries<>(new DataPoint[]{});
       // graph1.getGridLabelRenderer().setLabelVerticalWidth(95);
        graph1.setTitle("TEMPERATURES");
        graph1.setTitleTextSize(20);

        graph1.getLegendRenderer().setAlign(LegendRenderer.LegendAlign.TOP);
        graph1.addSeries(series);
        graph1.addSeries(series2);

        sgraph1.setChecked(false);
        //attach a listener to check for changes in state
        sgraph1.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {

            @Override
            public void onCheckedChanged(CompoundButton buttonView,
                                         boolean isChecked) {

                if(isChecked){
                    graph1.getLegendRenderer().setVisible(true);
                  //  graph1.getLegendRenderer().setFixedPosition(-115, -30);
                    graph1.getLegendRenderer().setPadding(10);
                    series.setTitle(editText4.getText().toString());
                    series.setColor(Color.GREEN);
                    series.setDrawDataPoints(true);
                    series.setDataPointsRadius(5);
                    series.setThickness(8);

                    Toast.makeText(graphActivity.this, "Series1 enabled ", Toast.LENGTH_LONG).show();
                }else if (!isChecked){

                    graph1.getLegendRenderer().setVisible(false);

                    Toast.makeText(graphActivity.this, "Series1 disabled ", Toast.LENGTH_LONG).show();
                }

            }
        });
        series.setOnDataPointTapListener(new OnDataPointTapListener() {
        //   @Override
           public void onTap(Series series, DataPointInterface dataPoint) {
                Toast.makeText(graphActivity.this, "Series1: On Data Point clicked: " + dataPoint, Toast.LENGTH_SHORT).show();

            }

        });

        sgraph2.setChecked(false);
        //attach a listener to check for changes in state
        sgraph2.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {

            @Override
            public void onCheckedChanged(CompoundButton buttonView,
                                         boolean isChecked) {

                if(isChecked){
                    graph1.getLegendRenderer().setVisible(true);
                 //   graph1.getLegendRenderer().setFixedPosition(-115, -30);
                    graph1.getLegendRenderer().setPadding(10);
                    series2.setTitle(editText5.getText().toString());
                    series2.setColor(Color.RED);
                    series2.setDrawDataPoints(true);
                    series2.setDataPointsRadius(5);
                    series2.setThickness(8);

                    Toast.makeText(graphActivity.this, "Series2 enabled ", Toast.LENGTH_LONG).show();
                }else if (!isChecked){

                    graph1.getLegendRenderer().setVisible(false);

                    Toast.makeText(graphActivity.this, "Series2 disabled ", Toast.LENGTH_LONG).show();
                }

            }
        });
        series2.setOnDataPointTapListener(new OnDataPointTapListener() {
            //   @Override
            public void onTap(Series series, DataPointInterface dataPoint) {
                Toast.makeText(graphActivity.this, "Series2: On Data Point clicked: " + dataPoint, Toast.LENGTH_SHORT).show();

            }

        });

    }`

My set method:
`public void SET(View view) {

       MINY=Integer.parseInt(editText2.getText().toString());
        MAXY=Integer.parseInt(editText3.getText().toString());
        graph1.getViewport().setXAxisBoundsManual(true);
        graph1.getViewport().setMinX(0);
        graph1.getViewport().setMaxX(20);
        graph1.getViewport().setYAxisBoundsManual(true);
        graph1.getViewport().setMinY(MINY);
        graph1.getViewport().setMaxY(MAXY);
       // graph1.getViewport().setScalable(true);
        graph1.getViewport().setScrollable(true);
      //  graph1.getViewport().scrollToEnd();
        Toast.makeText(graphActivity.this,"MAX/MIN AXIS SETTED", Toast.LENGTH_LONG).show();

    }`

and my post method:

`protected void onPostExecute(String result) {
           // Toast.makeText(graphActivity.this, result, Toast.LENGTH_LONG).show();
            textStatus.setText(result);
           myNum= Double.parseDouble(result);

            mytime= mytime+1;

          
            series.appendData(new DataPoint(mytime*1d ,myNum),true,800);

         

            }`

**Comment by GeorgeSia** [comment]
my error from debugger is:
06-21 02:30:18.934 11834-11834/com.axinar.axinar E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   java.lang.NullPointerException
                                                                       at com.jjoe64.graphview.series.BaseSeries$1.<init>(BaseSeries.java:183)
                                                                       at com.jjoe64.graphview.series.BaseSeries.getValues(BaseSeries.java:170)
                                                                       at com.jjoe64.graphview.series.LineGraphSeries.draw(LineGraphSeries.java:171)
                                                                       at com.jjoe64.graphview.GraphView.onDraw(GraphView.java:298)
                                                                       at android.view.View.draw(View.java:13712)
                                                                       at android.view.View.getDisplayList(View.java:12650)
                                                                       at android.view.View.getDisplayList(View.java:12694)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
                                                                       at android.view.View.getDisplayList(View.java:12588)
                                                                       at android.view.View.getDisplayList(View.java:12694)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
                                                                       at android.view.View.getDisplayList(View.java:12588)
                                                                       at android.view.View.getDisplayList(View.java:12694)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
                                                                       at android.view.View.getDisplayList(View.java:12588)
                                                                       at android.view.View.getDisplayList(View.java:12694)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
                                                                       at android.view.View.getDisplayList(View.java:12588)
                                                                       at android.view.View.getDisplayList(View.java:12694)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
                                                                       at android.view.View.getDisplayList(View.java:12588)
                                                                       at android.view.View.getDisplayList(View.java:12694)
                                                                       at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:2910)
                                                                       at android.view.View.getDisplayList(View.java:12588)
                                                                       at android.view.View.getDisplayList(View.java:12694)
                                                                       at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java:1198)
                                                                       at android.view.ViewRootImpl.draw(ViewRootImpl.java:2173)
                                                                       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2045)
                                                                       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1854)
                                                                       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:989)
                                                                       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:4351)
                                                                       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
                                                                       at android.view.Choreographer.doCallbacks(Choreographer.java:562)
                                                                       at android.view.Choreographer.doFrame(Choreographer.java:532)
                                                                       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
                                                                       at android.os.Handler.handleCallback(Handler.java:725)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                       at android.os.Looper.loop(Looper.java:137)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:511)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                       at dalvik.system.NativeStart.main(Native Method)
